In [9]:
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv('Bengaluru_House_Data.xls')

In [11]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [12]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [13]:
df.value_counts()

area_type             availability   location              size   society  total_sqft  bath  balcony  price
Super built-up  Area  Ready To Move  Haralur Road          2 BHK  RInceeg  1243        2.0   2.0      46.00     10
                                     HSR Layout            2 BHK  NRosete  1140        2.0   2.0      46.00      9
                                     Parappana Agrahara    2 BHK  Peide L  1194        2.0   2.0      47.00      7
                      21-Dec         Kanakpura Road        3 BHK  PrarePa  1100        3.0   2.0      53.00      5
                      18-Sep         Chandapura            1 BHK  SunceEs  645         1.0   1.0      16.45      5
                                                                                                                ..
                      Ready To Move  Yeshwanthpur          3 BHK  IBityin  2559        3.0   2.0      141.00     1
                                                                  RNvasth  1852        3.0   2.0      160.00     1
                                                                           1856        4.0   2.0      180.00     1
                                                                  Saade E  1523        3.0   3.0      170.00     1
Built-up  Area        15-Jun         Outer Ring Road East  3 BHK  SRzonhu  1500        2.0   0.0      97.00      1
Name: count, Length: 7144, dtype: int64

In [14]:
df.shape

(13320, 9)

In [15]:
# Missing values
missing_values = df.isnull().sum()

# Show columns with missing values
missing_values[missing_values > 0]

location       1
size          16
society     5502
bath          73
balcony      609
dtype: int64

In [16]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [17]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [18]:
df.drop(
    ['area_type', 'availability', 'society'],
    axis=1,
    inplace=True
)

In [19]:
df

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13316             Richards Town      4 BHK       3600   5.0      NaN  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[13320 rows x 6 columns]

In [20]:
df.head()

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [21]:
df.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [22]:
df.dropna(inplace=True)

In [23]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [24]:
df

                       location       size total_sqft  bath  balcony   price
0      Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                      Kothanur      2 BHK       1200   2.0      1.0   51.00
...                         ...        ...        ...   ...      ...     ...
13314         Green Glen Layout      3 BHK       1715   3.0      3.0  112.00
13315                Whitefield  5 Bedroom       3453   4.0      0.0  231.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0      1.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0      1.0  488.00
13319              Doddathoguru      1 BHK        550   1.0      1.0   17.00

[12710 rows x 6 columns]

In [25]:
df.shape

(12710, 6)

In [26]:
df['size'].unique()[:10]

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom'], dtype=object)

In [27]:
df['bhk'] = df['size'].str.split().str[0].astype(int)

In [28]:
df

,location,size,total_sqft,bath,balcony,price,bhk
0,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2
1,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4
2,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3
3,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3
4,Kothanur,2 BHK,1200,2.0,1.0,51.00,2
...,...,...,...,...,...,...,...
13314,Green Glen Layout,3 BHK,1715,3.0,3.0,112.00,3
13315,Whitefield,5 Bedroom,3453,4.0,0.0,231.00,5
13317,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00,2
13318,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00,4
13319,Doddathoguru,1 BHK,550,1.0,1.0,17.00,1

In [29]:
def convert_sqft_to_num(x):
    
    tokens = x.split('-')
    
    # Case 1: Range values like "2100 - 2850"
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    
    # Case 2: Normal numeric values
    try:
        return float(x)
    
    # Case 3: Invalid values
    except:
        return None

In [30]:
df['total_sqft'] = df['total_sqft'].apply(convert_sqft_to_num)

In [31]:
df['total_sqft'].isnull().sum()

np.int64(42)

In [32]:
df = df[df['total_sqft'].notnull()]

In [33]:
df.drop('size', axis=1, inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_17204\1877746914.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('size', axis=1, inplace=True)

In [34]:
df.head()

                   location  total_sqft  bath  balcony   price  bhk
0  Electronic City Phase II      1056.0   2.0      1.0   39.07    2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00    4
2               Uttarahalli      1440.0   2.0      3.0   62.00    3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00    3
4                  Kothanur      1200.0   2.0      1.0   51.00    2

In [35]:
df.dtypes

location       object
total_sqft    float64
bath          float64
balcony       float64
price         float64
bhk             int64
dtype: object

In [36]:
df

                       location  total_sqft  bath  balcony   price  bhk
0      Electronic City Phase II      1056.0   2.0      1.0   39.07    2
1              Chikka Tirupathi      2600.0   5.0      3.0  120.00    4
2                   Uttarahalli      1440.0   2.0      3.0   62.00    3
3            Lingadheeranahalli      1521.0   3.0      1.0   95.00    3
4                      Kothanur      1200.0   2.0      1.0   51.00    2
...                         ...         ...   ...      ...     ...  ...
13314         Green Glen Layout      1715.0   3.0      3.0  112.00    3
13315                Whitefield      3453.0   4.0      0.0  231.00    5
13317     Raja Rajeshwari Nagar      1141.0   2.0      1.0   60.00    2
13318           Padmanabhanagar      4689.0   4.0      1.0  488.00    4
13319              Doddathoguru       550.0   1.0      1.0   17.00    1

[12668 rows x 6 columns]

In [37]:
df['price_per_sqft'] = (df['price'] * 100000) / df['total_sqft']

C:\Users\Asus\AppData\Local\Temp\ipykernel_17204\2456710443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = (df['price'] * 100000) / df['total_sqft']

In [38]:
df

,location,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.810606
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.384615
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.555556
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.890861
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.000000
...,...,...,...,...,...,...,...
13314,Green Glen Layout,1715.0,3.0,3.0,112.00,3,6530.612245
13315,Whitefield,3453.0,4.0,0.0,231.00,5,6689.834926
13317,Raja Rajeshwari Nagar,1141.0,2.0,1.0,60.00,2,5258.545136
13318,Padmanabhanagar,4689.0,4.0,1.0,488.00,4,10407.336319
13319,Doddathoguru,550.0,1.0,1.0,17.00,1,3090.909091

In [39]:
df['location'].value_counts()

location
Whitefield          513
Sarjapur  Road      372
Electronic City     300
Kanakpura Road      259
Thanisandra         230
                   ...
Medaralli             1
Govindraja Nagar      1
Chikkajala            1
Udayagiri             1
LIC Colony            1
Name: count, Length: 1259, dtype: int64

In [40]:
location_stats = df['location'].value_counts()

location_stats_less_than_10 = location_stats[location_stats <= 10]

df['location'] = df['location'].apply(
    lambda x: 'other' if x in location_stats_less_than_10 else x
)

C:\Users\Asus\AppData\Local\Temp\ipykernel_17204\3864957542.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['location'] = df['location'].apply(

In [41]:
df = df[df.total_sqft / df.bhk > 300]

In [42]:
import numpy as np
import pandas as pd

def remove_pps_outliers(df):
    df_out = pd.DataFrame()

    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)

        reduced_df = subdf[
            (subdf.price_per_sqft > (m - st)) &
            (subdf.price_per_sqft <= (m + st))
        ]

        df_out = pd.concat([df_out, reduced_df], ignore_index=True)

    return df_out

df = remove_pps_outliers(df)

In [43]:
df = pd.get_dummies(df, columns=['location'])

In [44]:
X = df.drop('price', axis=1)
y = df['price']

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [46]:
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

LinearRegression()

In [47]:
y_pred = lr_model.predict(X_test)

In [48]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_pred)

print(score)

0.9253295339556096

In [49]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor()

rf_model.fit(X_train, y_train)

RandomForestRegressor()

In [52]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.6/101.7 MB 8.9 MB/s eta 0:00:12
   - -------------------------------------- 3.1/101.7 MB 7.8 MB/s eta 0:00:13
   - -------------------------------------- 4.5/101.7 MB 7.2 MB/s eta 0:00:14
   -- ------------------------------------- 5.8/101.7 MB 6.9 MB/s eta 0:00:14
   -- ------------------------------------- 7.1/101.7 MB 6.7 MB/s eta 0:00:15
   --- ------------------------------------ 8.1/101.7 MB 6.7 MB/s eta 0:00:15
   --- ------------------------------------ 9.4/101.7 MB 6.6 MB/s eta 0:00:14
   ---- ----------------------------------- 11.0/101.7 MB 6.6 MB/s eta 0:00:14
   ---- ----------------------------------- 12.3/101.7 MB 6.5 MB/s eta 0:00:14
   ----- ---------------------------------- 13.1/101.7 MB 6.3 MB/s eta 0:00:15
   ----- ---------------------------------- 14.2/101.7 MB 6.1 MB/s eta 0:00:15
   ----- ---------------------------------- 14.9/101.7 MB 6.0 MB/s eta 0:00:15
   ------ --------------------------------- 15.7/101.7 MB 5.9 MB/s eta 0:00:15
   ------- -------------------------------- 17.8/101.7 MB 6.0 MB/s eta 0:00:14
   ------- -------------------------------- 19.1/101.7 MB 6.0 MB/s eta 0:00:14
   ------- -------------------------------- 20.2/101.7 MB 6.0 MB/s eta 0:00:14
   -------- ------------------------------- 21.2/101.7 MB 5.9 MB/s eta 0:00:14
   -------- ------------------------------- 22.3/101.7 MB 5.8 MB/s eta 0:00:14
   -------- ------------------------------- 22.8/101.7 MB 5.7 MB/s eta 0:00:14
   --------- ------------------------------ 23.3/101.7 MB 5.5 MB/s eta 0:00:15
   --------- ------------------------------ 24.1/101.7 MB 5.4 MB/s eta 0:00:15
   ---------- ----------------------------- 25.7/101.7 MB 5.5 MB/s eta 0:00:14
   ---------- ----------------------------- 27.3/101.7 MB 5.6 MB/s eta 0:00:14
   ----------- ---------------------------- 28.3/101.7 MB 5.5 MB/s eta 0:00:14
   ----------- ---------------------------- 29.4/101.7 MB 5.5 MB/s eta 0:00:14
   ----------- ---------------------------- 29.6/101.7 MB 5.4 MB/s eta 0:00:14
   ----------- ---------------------------- 29.9/101.7 MB 5.2 MB/s eta 0:00:14
   ----------- ---------------------------- 30.4/101.7 MB 5.1 MB/s eta 0:00:14
   ------------ --------------------------- 31.5/101.7 MB 5.1 MB/s eta 0:00:14
   ------------ --------------------------- 33.0/101.7 MB 5.2 MB/s eta 0:00:14
   ------------- -------------------------- 34.6/101.7 MB 5.2 MB/s eta 0:00:13
   -------------- ------------------------- 35.7/101.7 MB 5.2 MB/s eta 0:00:13
   -------------- ------------------------- 37.2/101.7 MB 5.3 MB/s eta 0:00:13
   --------------- ------------------------ 38.3/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 39.1/101.7 MB 5.3 MB/s eta 0:00:12
   --------------- ------------------------ 40.1/101.7 MB 5.3 MB/s eta 0:00:12
   ---------------- ----------------------- 40.9/101.7 MB 5.2 MB/s eta 0:00:12
   ---------------- ----------------------- 42.7/101.7 MB 5.3 MB/s eta 0:00:12
   ----------------- ---------------------- 43.8/101.7 MB 5.3 MB/s eta 0:00:11
   ----------------- ---------------------- 44.8/101.7 MB 5.3 MB/s eta 0:00:11
   ------------------ --------------------- 46.7/101.7 MB 5.4 MB/s eta 0:00:11
   ------------------ --------------------- 47.7/101.7 MB 5.3 MB/s eta 0:00:11
   ------------------- -------------------- 49.0/101.7 MB 5.4 MB/s eta 0:00:10
   ------------------- -------------------- 50.1/101.7 MB 5.4 MB/s eta 0:00:10
   -------------------- ------------------- 51.1/101.7 MB 5.3 MB/s eta 0:00:10
   -------------------- ------------------- 52.4/101.7 MB 5.4 MB/s eta 0:00:10
   --------------------- ------------------ 53.5/101.7 MB 5.3 MB/s eta 0:00:10
   --------------------- ------------------ 54.3/101.7 MB 5.3 MB/s eta 0:00:09
   --------------------- ------------------ 54.8/101.7 MB 5.3 MB/s eta 0:00:09
   --------------------- ------------------ 55.6/101.7 MB 5.2 MB/s eta 0:00:09
   ---------------------- ----------------- 56.4/101.7 MB 5.2 MB/s eta 0:00:09
   ---------------------- ----------------- 57.4/101.7 MB 5.2 MB/s eta 0:00:09
   ---------------------- ----------------- 58.5/101.7 MB 5.2 MB/s eta 0:00:09
   ----------------------- ---------------- 60.0/101.7 MB 5.2 MB/s eta 0:00:08
   ------------------------ --------------- 61.6/101.7 MB 5.3 MB/s eta 0:00:08
   ------------------------ --------------- 62.9/101.7 MB 5.3 MB/s eta 0:00:08
   ------------------------- -------------- 64.2/101.7 MB 5.3 MB/s eta 0:00:08
   ------------------------- -------------- 65.8/101.7 MB 5.3 MB/s eta 0:00:07
   -------------------------- ------------- 66.8/101.7 MB 5.3 MB/s eta 0:00:07
   -------------------------- ------------- 68.4/101.7 MB 5.4 MB/s eta 0:00:07
   --------------------------- ------------ 69.7/101.7 MB 5.4 MB/s eta 0:00:06
   --------------------------- ------------ 70.8/101.7 MB 5.4 MB/s eta 0:00:06
   ---------------------------- ----------- 72.4/101.7 MB 5.4 MB/s eta 0:00:06
   ---------------------------- ----------- 73.7/101.7 MB 5.4 MB/s eta 0:00:06
   ----------------------------- ---------- 75.2/101.7 MB 5.4 MB/s eta 0:00:05
   ------------------------------ --------- 76.5/101.7 MB 5.4 MB/s eta 0:00:05
   ------------------------------ --------- 77.9/101.7 MB 5.4 MB/s eta 0:00:05
   ------------------------------- -------- 79.2/101.7 MB 5.5 MB/s eta 0:00:05
   ------------------------------- -------- 80.5/101.7 MB 5.5 MB/s eta 0:00:04
   -------------------------------- ------- 81.8/101.7 MB 5.5 MB/s eta 0:00:04
   -------------------------------- ------- 83.1/101.7 MB 5.5 MB/s eta 0:00:04
   --------------------------------- ------ 84.4/101.7 MB 5.5 MB/s eta 0:00:04
   --------------------------------- ------ 86.0/101.7 MB 5.5 MB/s eta 0:00:03
   ---------------------------------- ----- 87.3/101.7 MB 5.5 MB/s eta 0:00:03
   ---------------------------------- ----- 88.6/101.7 MB 5.5 MB/s eta 0:00:03
   ----------------------------------- ---- 89.9/101.7 MB 5.5 MB/s eta 0:00:03
   ----------------------------------- ---- 91.2/101.7 MB 5.5 MB/s eta 0:00:02
   ------------------------------------ --- 92.5/101.7 MB 5.6 MB/s eta 0:00:02
   ------------------------------------ --- 93.6/101.7 MB 5.6 MB/s eta 0:00:02
   ------------------------------------- -- 94.9/101.7 MB 5.6 MB/s eta 0:00:02
   ------------------------------------- -- 96.5/101.7 MB 5.6 MB/s eta 0:00:01
   -------------------------------------- - 97.8/101.7 MB 5.6 MB/s eta 0:00:01
   -------------------------------------- - 99.1/101.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 5.5 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [53]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor()

xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [54]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Dictionary of models
models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(),
    "XGBoost": XGBRegressor()
}

# Train and evaluate
for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Metrics
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    # Print results
    print(f"\n{name}")
    print("R2 Score:", r2)
    print("MAE:", mae)
    print("RMSE:", rmse)

Linear Regression
R2 Score: 0.9253295339556096
MAE: 9.16269029448085
RMSE: 20.16947525102552

Random Forest
R2 Score: 0.9851802653602434
MAE: 1.1199388946281006
RMSE: 8.985461382192224

XGBoost
R2 Score: 0.9664982695191241
MAE: 2.45466332524276
RMSE: 13.509951458103181

In [55]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

params = {
    'n_estimators': [50, 100],
    'max_depth': [10, 20, None]
}

grid = GridSearchCV(
    RandomForestRegressor(),
    params,
    cv=5
)

grid.fit(X_train, y_train)

print(grid.best_params_)

{'max_depth': 10, 'n_estimators': 50}

In [56]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    best_model,
    X,
    y,
    cv=5
)

print(scores)
print(scores.mean())

NameError: name 'best_model' is not defined

In [57]:
best_model = xgb_model

In [58]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    best_model,
    X,
    y,
    cv=5
)

print(scores)
print(scores.mean())

[0.93011014 0.96765821 0.90387422 0.92805534 0.86616506]
0.9191725958876591

In [59]:
import joblib

joblib.dump(best_model, 'house_price_model.pkl')

['house_price_model.pkl']

In [60]:
columns = X.columns

In [61]:
import joblib

joblib.dump(columns, "model_columns.pkl")

['model_columns.pkl']